services:
  balancer:
    image: ghcr.io/ystv/balancer:latest
    ports:
      - 3000:3000
    environment:
      BALANCER_HOSTNAME: web0
      BALANCER_EXTERNAL_URL: https://balancer.example.com
      BALANCER_CONSUL_AGENT_URL: http://localhost:8500
      BALANCER_CONSUL_KV_PREFIX: balancer
      BALANCER_CONSUL_SERVICE_NAME: balancer
      BALANCER_HTTP_ADDRESS: 0.0.0.0
      BALANCER_HTTP_PORT: 3000
